### ISSUE TITLE
gtburst hangs, not doing Likelihood Analysis

### ISSUE THREAD

**Issue by nyctophile-aayu** [fermi-lat/pyBurstAnalysisGUI#10]
Hi Guys,

I have encountered a strange issue with the gtburst tool. Whenever I pick any GRB and start performing Likelihood Analysis, then after clicking on Run, it hangs. Also, generate an error. I have tried multiple re-installation of Fermitools but the issue is not resolving. If anybody have any idea, what is causing this error and how to fix this. Then please help me.

Regards,
Ayush
![Screenshot from 2023-05-11 17-27-35](https://github.com/fermi-lat/pyBurstAnalysisGUI/assets/101836465/b1d98c76-e0b8-4f1d-84f7-7ec479c78f2f)
![Screenshot from 2023-05-11 17-27-16](https://github.com/fermi-lat/pyBurstAnalysisGUI/assets/101836465/7971dbc0-244f-4439-84a8-4c660eda8e2c)
[gtburst.log](https://github.com/fermi-lat/pyBurstAnalysisGUI/files/11451869/gtburst.log)

**Comment by nmirabal** [comment]
Please try 
conda create -n fermicurrent -c conda-forge -c fermi fermitools numpy=1.20

**Comment by nyctophile-aayu** [comment]
I have tried that, it is giving me the same error as mentioned before:


ubuntu@ubuntu-HP-Z2-Tower-G9-Workstation-Desktop-PC:~ $ conda activate fermicurrent
(fermicurrent) ubuntu@ubuntu-HP-Z2-Tower-G9-Workstation-Desktop-PC:~ $ gtburst

Loading pyBurstAnalysisGUI v. 03-00-00p5 .....Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/fermicurrent/bin/gtburst", line 7, in <module>
    from fermitools.gtburst import main
  File "/home/ubuntu/anaconda3/envs/fermicurrent/lib/python3.9/site-packages/fermitools/gtburst.py", line 73, in <module>
    from GtBurst import dataHandling
  File "/home/ubuntu/anaconda3/envs/fermicurrent/lib/python3.9/site-packages/fermitools/GtBurst/dataHandling.py", line 16, in <module>
    import BinnedAnalysis
  File "/home/ubuntu/anaconda3/envs/fermicurrent/lib/python3.9/site-packages/fermitools/BinnedAnalysis.py", line 13, in <module>
    import pyLikelihood as pyLike
  File "/home/ubuntu/anaconda3/envs/fermicurrent/lib/python3.9/site-packages/fermitools/pyLikelihood.py", line 15, in <module>
    import _pyLikelihood
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory


Please suggest what could be the possible cause for it and how to resolve it. Also, I wish to know as it is an alternative, so why won't fermitools=2.2.0 work?

**Comment by jasercion** [comment]
This should be resolved as of the latest release.  If it still occurs please reopen the issue and tag me.
